### ISSUE TITLE
Documentation needed.

### ISSUE THREAD

**Issue by swirlsky** [formly-js/ng-formly#511] opened 2017-09-07 11:56 UTC
**I'm submitting a ...**
[x] support request

**Current behavior**
The Introductory Example under https://ng2.angular-formly.com/guides/introductory-example.html says that "This is a small subset of the things that formly can do :-) See the other examples and the documentation for more." The problem is that I cannot find a documentation anywhere. Which form elements the module supports, how the JSON schema should look like, etc.

**Expected behavior**
Maybe I am blind for not finding the docs, or if there really isn't any, could you please provide at least some basics?

**What is the motivation / use case for changing the behavior?**
The module seems very promising, but without docs I don't know where and how to begin.

**Comment by aitboudad** [comment] 2017-09-07 12:13
duplicate of #509,  once we finish with `v2` we will focus on the documentation also we need some help :).

**Closed by aitboudad** 2017-09-07 12:13 UTC
