### ISSUE TITLE
repeatSection validation issue

### ISSUE THREAD

**Issue by nikul1993** [formly-js/ng-formly#451] opened 2017-06-19 13:33 UTC
Hello team,

when i use repeatSection at that time ValidationService.emailValidator can not working and when new section add that time select box placeholder not display.

thanks

**Comment by aitboudad** [comment] 2017-06-21 09:42
I think I know what's happen, I'm working on a fix!

**Comment by aitboudad** [comment] 2017-06-21 10:16
see #456

**Comment by nikul1993** [comment] 2017-06-21 11:48
@aitboudad 

thanks for your solution and we really appreciate you But i am facing another issue. I have two issues in repeat section.

1)  when you use ValidationService in repeat section then it`s not working here is my code.

{
				className: 'col-sm-4 col-xs-12',
				key: 'email',
				type: 'input',
				templateOptions: {
					type: 'email',
					label: 'E-Mail',
					placeholder: 'E-Mail or User Name *',					
					addonRight: {
						class: 'fa fa-envelope',
						onClick: (to, fieldType, $event) => console.log(to, fieldType, $event),
					},
				},
				validators: {
					validation: Validators.compose([Validators.required, *ValidationService.emailValidator*])
				}
				
			},

 2) When i use repeat functionality in selectbox I face placeholder or default selected option issue. It shows blank value in first option can you please check it
{
				className: 'col-sm-4 col-xs-12',
				key: 'loginoption',
				type: 'select',
				templateOptions: {
					options: [{
						label: 'Skype',
						value: 'skype',
					}, {
						label: 'Yahoo',
						value: 'yahoo',
					}, {
						label: 'Google Hangouts',
						value: 'google hangouts',
					}, ],
					label: 'Login Option',
					placeholder: 'Login Option *',
					addonRight: {
						class: 'fa fa-caret-down',
						onClick: (to, fieldType, $event) => console.log(to, fieldType, $event),
					},
				},
			}, 

thanks again for your support :)

**Comment by aitboudad** [comment] 2017-06-21 12:15
1. fixed by #457 
2. I'll look into it later

**Comment by nikul1993** [comment] 2017-06-27 07:08
Hello @aitboudad 

hope you are doing good..
have you get chance to look on second issue.

Thanks,

**Comment by aitboudad** [comment] 2017-06-27 08:23
sorry, not yet :(

**Comment by nikul1993** [comment] 2017-07-10 05:37
Hello @aitboudad

hope you are doing good..
have you get chance to look on second issue, which we discussed few weeks ago, actually its bit important for me to execute and get solution on above issues.

Thanks,

**Comment by aitboudad** [comment] 2017-07-10 09:04
I'm on it right now!

**Comment by aitboudad** [comment] 2017-07-10 09:50
fixed by #476, can you please check it, thanks!

**Comment by nikul1993** [comment] 2017-07-10 11:51
Hello @aitboudad 

It's working on repeated section but at first time select box placeholder not showing.

**Comment by aitboudad** [comment] 2017-07-10 12:02
> but at first time select box placeholder not showing.

It's depend on the provided value, can you check it if it's `undefined` ?

**Comment by nikul1993** [comment] 2017-07-10 12:24
Hello @aitboudad 

I didn't provide the value to the select box. 

it show the templateOptions{ placeholder:'Login Option *' }. and when i provide the value to the select box in repeated section it replace with placeholder.

**Comment by aitboudad** [comment] 2017-07-10 12:37
I'm not able to reproduce you issue, can you please provide me an example ?

**Comment by nikul1993** [comment] 2017-07-10 13:15
Hello @aitboudad 

Please check this https://plnkr.co/edit/mmosJfWLteJg99g0eUYM?p=preview .

in this example input placeholder repeat but select box placeholder not.

**Comment by aitboudad** [comment] 2017-07-10 14:27
I was expected the empty value is `undefined` so it's depend on the use-case, in your example it's empty string '' so I think the issue can be solved by using `defaultValue`:
```patch
{
    className: 'col-sm-4 col-xs-12',
    key: 'loginoption',
    type: 'select',
++  defaultValue: '',
}

**Comment by aitboudad** [comment] 2017-07-10 17:11
Please reopen if you still got the issue

**Closed by aitboudad** 2017-07-10 17:11 UTC
Labels: bug

**Comment by nikul1993** [comment] 2017-07-11 06:51
Thanks @aitboudad it is working.
