### ISSUE TITLE
ERROR Error: Cannot find control with unspecified name attribute

### ISSUE THREAD

**Issue by werts** [formly-js/ng-formly#516] opened 2017-09-17 07:46 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

when use multicheckbox with its options loaded async.i can see some errors from chrome console.and its too long to desplay,and i try to set up a plunker,but it's much complex,because there is no error when options are presented in template fields.

**Expected behavior**

no error in chrome console,and may not affect another code.and i guess the multichekbox doesnt has an attribute of 'name'

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

windows 10
npm 5.3.3
node 7.2.0

* **Angular version:** 2.0.X

4.3.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 2.4.0

* **Node (for AoT issues):** `node --version` =

**Comment by franzeal** [comment] 2017-09-18 03:39
Here's a plunker to illustrate the issue (commented out on line 60 of src/app.ts) as well as to demonstrate a workaround:
https://plnkr.co/edit/L3w41KBdYQ5F0Fwb9kQz?p=preview

The problem is that the built-in type does not update its underlying Angular form beyond initialization.  The built-in type should either be updated to support this scenario or you could override the type like I did in the plunker with your own fix.

**Comment by werts** [comment] 2017-09-20 08:07
@franzeal is this built-in-type included in the new component? anyway, thanks a lot.I got error from your plunk code as you presented that 'field is not defined'
the error code may be come from :'[formlyAttributes]="field" '
, and i removed the field input, there is no error now, but i can't set defaultValue later.
ng-formly version:1.0.0-rc.12

**Comment by franzeal** [comment] 2017-09-23 04:31
Not sure what you're asking.  The built-in type is part of ng-formly, it can be overridden as in the example I provided or it can be fixed by submitting a PR.

I'm not seeing the any error in the plunk.  Maybe I'm just missing it, but are there some steps I need to perform to see it?

If you wanted to tweak the plunk, I'll take another look.

**Closed** 2017-10-20 17:04 UTC
Labels: flag: can be closed?

**Comment by james-poulose** [comment] 2018-12-04 03:18
This can also happen because of a typo in the `key` name. Check this [https://github.com/formly-js/ngx-formly/issues/1023#issuecomment-443955620](url)
